apiVersion: v1
kind: Service
metadata:
  name: secure-api-service 
spec:
  selector:
    app: secure-api
  ports:
    - protocol: TCP
      port: 80 # Port expos√© par le cluster
      targetPort: 8080 # Port du conteneur
  type: LoadBalancer # Simule une IP externe